stages:
  - build


builder:
  stage: build
  script:
  - mvn install
  - docker build --no-cache -t docker.artifactory.dev.widi/windtre/cms-3mobility:$CI_COMMIT_REF_NAME .
  - docker push docker.artifactory.dev.widi/windtre/cms-3mobility:$CI_COMMIT_REF_NAME
  only:
  - tags
