stages:
  - build


builder:
  stage: build
  script:
  - mvn install
  - docker build --no-cache --build-arg version=${CI_COMMIT_REF_NAME} -t docker.artifactory.wind-digital.com/windtre/cms3mobility:${CI_COMMIT_REF_NAME} .
  - docker push docker.artifactory.wind-digital.com/windtre/cms3mobility:${CI_COMMIT_REF_NAME}
  only:
  - tags
